<?php defined ( 'SYSPATH' ) or die ( 'No direct access allowed.' );
$config = array (
  12101 => 
  array (
    'id' => '12101',
    'name' => '桑尼号',
    'type' => '21',
    'quality' => '5',
    'needLevel' => '1',
    'iconID' => 'sPropItem_12101',
    'resID' => 'sPropRes_12101',
    'validTime' => '604800',
    'maxNum' => '1',
    'hp' => '2000',
    'atk' => '0',
    'def' => '0',
    'hitRate' => '0',
    'avoidRate' => '0',
    'critRate' => '0',
    'saleSort' => '0',
    'isHot' => '0',
    'value' => '100000',
    'price' => '100',
    'about' => '描述啊描述',
  ),
  12201 => 
  array (
    'id' => '12201',
    'name' => '火神炮',
    'type' => '22',
    'quality' => '3',
    'needLevel' => '1',
    'iconID' => 'sPropItem_12201',
    'resID' => '0',
    'validTime' => '0',
    'maxNum' => '1',
    'hp' => '0',
    'atk' => '20',
    'def' => '0',
    'hitRate' => '0',
    'avoidRate' => '0',
    'critRate' => '0',
    'saleSort' => '0',
    'isHot' => '0',
    'value' => '100000',
    'price' => '100',
    'about' => '描述啊描述',
  ),
  12301 => 
  array (
    'id' => '12301',
    'name' => '铸铁弹',
    'type' => '23',
    'quality' => '3',
    'needLevel' => '1',
    'iconID' => 'sPropItem_12301',
    'resID' => 'sPropRes_12301',
    'validTime' => '0',
    'maxNum' => '1',
    'hp' => '0',
    'atk' => '0',
    'def' => '0',
    'hitRate' => '10',
    'avoidRate' => '0',
    'critRate' => '10',
    'saleSort' => '0',
    'isHot' => '0',
    'value' => '100000',
    'price' => '100',
    'about' => '描述啊描述',
  ),
  12401 => 
  array (
    'id' => '12401',
    'name' => '神圣巨木护板',
    'type' => '24',
    'quality' => '4',
    'needLevel' => '1',
    'iconID' => 'sPropItem_12401',
    'resID' => '0',
    'validTime' => '0',
    'maxNum' => '1',
    'hp' => '0',
    'atk' => '0',
    'def' => '20',
    'hitRate' => '0',
    'avoidRate' => '10',
    'critRate' => '0',
    'saleSort' => '0',
    'isHot' => '0',
    'value' => '100000',
    'price' => '100',
    'about' => '描述啊描述',
  ),
  12501 => 
  array (
    'id' => '12501',
    'name' => '王下七武海',
    'type' => '25',
    'quality' => '5',
    'needLevel' => '1',
    'iconID' => 'sPropItem_12501',
    'resID' => 'sPropRes_12501',
    'validTime' => '0',
    'maxNum' => '1',
    'hp' => '0',
    'atk' => '0',
    'def' => '0',
    'hitRate' => '0',
    'avoidRate' => '10',
    'critRate' => '0',
    'saleSort' => '0',
    'isHot' => '0',
    'value' => '100000',
    'price' => '100',
    'about' => '描述啊描述',
  ),
);